### PR TITLE
use "spdx-license-ids" module to DRY it up

### PR DESCRIPTION
**Pull request by shinnn**
I replaced [source/licenses.json](https://github.com/kemitchell/spdx.js/blob/bc722dc029607e07f761e7b6cda4e0c17d716c08/source/licenses.json) with [spdx-license-ids](https://github.com/shinnn/spdx-license-ids) module to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) it up.

spdx-license-ids has a [build script](https://github.com/shinnn/spdx-license-ids/blob/master/build.js) to fetch the latest SPDX license identifiers from http://spdx.org/licenses/. So we can easily follow the update of the original license list.

### CODE REVIEW

**Comment by kemitchell** [comment]
Greetings from San Francisco, @shinnn!

Thank you for the pull request, and for `spdx-license-ids`, which I have used in a few personal projects.

I hesitate to merge only because the list in this module is based on the PDF release of the spec, rather than the list at http://spdx.org/licenses, and I'm not sure if or how reliably the SPDX working groups will keep the two lists in sync. There is also a Git repository of license files at http://git.spdx.org/ that would ideally drive all lists.

I have added myself to the SPDX mailing lists, and am making a list of questions to ask those more directly involved. I will certainly ask about the policy for the HTML list and the feasibility of machine-readable license list updates.

**Comment by kemitchell** [comment]
@shinnn, I should mention that you may be interested in the following issues and pull requests:
- npm/normalize-package-data#61 (SPDX warnings for npm's metadata normalization function)
- npm/init-package-json#42 (SPDX validation and correction for the `npm init` wizard)
- npm/npm#6241
- npm/npm#4473

SPDX nerds assemble!

**Comment by shinnn** [comment]
Ah, I've mistaken. The build script fetches the list from the git repository, not the website!

https://github.com/sindresorhus/spdx-license-list/blob/31a7ddfac9e1fbef2e50b27504c4dedd339eaf1a/generate.js#L12

**Comment by kemitchell** [comment]
@shinnn, excellent! Thank you for your note. I see that the script parses the Excel file in the repository, which makes me sad, but also seems very realistic. I think that is where the working group's updates will begin life.

I will open an issue at `spdx-license-list` concerning semantic versions of the module and versions of the list. In the meantime, would you mind force-pushing a commit to lock the version of `spdx-license-list` in your PR to `"2.0.0"` (no caret or other semver range)?

**Comment by shinnn** [comment]
@kemitchell

> lock the version of spdx-license-list in your PR to "2.0.0" (no caret or other semver range)?

You meant `1.0.0`? OK, I'll remove `^`.

**Comment by kemitchell** [comment]
I believe the package is now at 2.0.0:

sindresorhus/spdx-license-list@50d904eb986a55616f21704d909f4f3f98d4147c

https://www.npmjs.com/package/spdx-license-list

**Comment by shinnn** [comment]
This PR adds `spdx-license-ids` module (not `spdx-license-list`) that is still v1.0.0. `spdx-license-list` is one of the modules used for building `spdx-license-ids`.

**Comment by kemitchell** [comment]
My mistake! Thank you for clarifying.

**Comment by shinnn** [comment]
> the script parses the Excel file in the repository, which makes me sad, but also seems very realistic.

Yeah. Ideally speaking, I'd like the SPDX working groups to provide an official JSON file (yes, of course, not .xls!) that includes the list of licenses.

**Comment by kemitchell** [comment]
@shinnn, if you would like to add yourself as a "contributor" in package.json, please feel free to do so.

**Pull request merged**
